"""
Shared chunked-read benchmark for the compressed 1-D image perf scripts.

Each data-model script (healsparse, random, ...) supplies its own
generator and then calls :func:`run_read_benchmark`, which runs the
three read regimes against the resulting file comparing rustfits to
fitsio.  The benchmark logic -- regimes, fresh-open-per-iteration
reader, correctness gate, table -- is identical across data models;
only the generated bytes differ, so it lives here once.

See the per-script docstrings for why the methodology is what it is
(release build, fresh open per iteration, FS-cache warmup).
"""

from __future__ import annotations

import os

import numpy as np
import rustfits

import _harness as h

DEFAULT_TILE = 1048576


def add_common_args(ap):
    """
    Register the args every compressed-read perf script shares.
    """
    ap.add_argument(
        "--file",
        help="read this existing .fits.fz instead of generating one",
    )
    ap.add_argument("--ntiles", type=int, default=h.env_int("PERF_NTILES", 64))
    ap.add_argument("--tile", type=int, default=DEFAULT_TILE)
    ap.add_argument(
        "--small-chunk", type=int, default=1000, help="sub-tile, partial"
    )
    ap.add_argument(
        "--mid-chunk", type=int, default=50000, help="sub-tile, whole"
    )
    ap.add_argument("--repeat", type=int, default=5)


def resolve_source(args, generate):
    """
    Return ``(fname, n, tile)``: open ``args.file`` if given, else call
    ``generate(fname, ntiles, tile) -> n`` (a closure with any
    data-model params already bound) to write a scratch file in CWD.
    """
    if args.file:
        fname = args.file
        with rustfits.FITS(fname) as f:
            hdu = f[1]
            n = int(hdu.shape[0])
            tile = int(hdu.compression.tile_shape[0])
        print(f"file: {fname} (n={n:,}, tile={tile:,})")
        return fname, n, tile

    fname = h.path("comp1d.fits.fz")
    tile = args.tile
    n = generate(fname, args.ntiles, tile)
    ratio = (n * 8) / os.path.getsize(fname)
    print(
        f"generated: n={n:,} ({n * 8 / 1e6:,.0f} MB raw), tile={tile:,}, "
        f"{os.path.getsize(fname) / 1e6:,.0f} MB on disk ({ratio:.1f}x)"
    )
    return fname, n, tile


def whole_ranges(n, chunk):
    return [(lo, min(lo + chunk, n)) for lo in range(0, n, chunk)]


def partial_ranges(n, chunk, cover):
    cover = min(n, cover)
    return [(lo, min(lo + chunk, cover)) for lo in range(0, cover, chunk)]


def run_read_benchmark(
    fname, n, tile, *, title, small_chunk=1000, mid_chunk=50000, repeat=5
):
    """
    Run the three read regimes against ``fname`` (rustfits vs fitsio).

    We OPEN A FRESH HANDLE inside every timed iteration so each tool
    starts with an empty tile cache and genuinely decodes.  Timing
    repeated reads of one open handle would instead measure fitsio's
    unbounded "cache every tile forever" hits against rustfits's bounded
    LRU re-decoding -- backwards from the real workload, which reads each
    tile once.  The harness's warmup pass primes the OS page (FS) cache
    first, so the timed passes read the compressed bytes from RAM and we
    measure decode-code speed, not the I/O-bound cold first read.
    """
    import fitsio

    # Correctness gate across a tile boundary before any timing.
    with rustfits.FITS(fname) as rf, fitsio.FITS(fname) as fi:
        lo, hi = tile - 500, tile + 500
        np.testing.assert_array_equal(rf[1][lo:hi], fi[1][lo:hi])

    def reader(mod, ranges):
        def run():
            with mod.FITS(fname) as f:
                hdu = f[1]
                for lo, hi in ranges:
                    hdu[lo:hi]

        return run

    # cover ~8 tiles for the small partial regime
    small_cover = min(n, 8 * tile)
    regimes = [
        (
            f"chunk {small_chunk} (partial, {small_cover // tile} tiles)",
            partial_ranges(n, small_chunk, small_cover),
        ),
        (
            f"chunk {mid_chunk} (whole array)",
            whole_ranges(n, mid_chunk),
        ),
        (
            f"chunk {tile} = tile (whole array)",
            whole_ranges(n, tile),
        ),
    ]

    results = []
    for label, ranges in regimes:
        nbytes = sum(hi - lo for lo, hi in ranges) * 8
        results.append(
            h.bench(
                label,
                reader(rustfits, ranges),
                run_fitsio=reader(fitsio, ranges),
                nbytes=nbytes,
                repeat=repeat,
            )
        )

    h.print_env()
    h.report(title, results)
